# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spmaC <- function(alpha, epi_abs, epi_rel, rho, lambda, iter, covF1, covF2, covF3, augIMat, p, M, setN, thetaF) {
    .Call('_SPMA_spmaC', PACKAGE = 'SPMA', alpha, epi_abs, epi_rel, rho, lambda, iter, covF1, covF2, covF3, augIMat, p, M, setN, thetaF)
}

